apiVersion: networking.istio.io/v1
kind: WorkloadGroup
metadata:
  name: payment
  namespace: mesh-workloads
spec:
  metadata:
    labels:
      app: payment
  template:
    serviceAccount: payment
    ports:
      http: 4000
